-- =============================================================================
-- REFFACTOR: ROLES Y PERMISOS (Soporte Multi-Role)
-- =============================================================================

-- 1. Crear tabla de Roles Maestros
-- Define los tipos de actores posibles en el sistema.
CREATE TABLE roles (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE, -- 'ADMIN', 'PROPIETARIO', 'INQUILINO', 'VIGILANTE'
    descripcion TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Insertar roles base del sistema
INSERT INTO roles (nombre, descripcion) VALUES 
('ADMIN', 'Administrador del sistema con acceso global o configurado'),
('PROPIETARIO', 'Titular de una o más unidades inmobiliarias'),
('INQUILINO', 'Residente o arrendatario de una unidad'),
('VIGILANTE', 'Personal de seguridad y control de accesos');

-- 3. Crear tabla intermedia Usuario_Roles (Many-to-Many)
-- Vincula usuarios con sus roles permitidos.
CREATE TABLE usuario_roles (
    usuario_id UUID REFERENCES usuarios(id) ON DELETE CASCADE,
    rol_id INT REFERENCES roles(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (usuario_id, rol_id)
);

-- NOTA: Una vez creada esta estructura, se deberá migrar la información 
-- de la columna 'usuarios.rol_sistema' actual a esta nueva tabla.
-- Ejemplo de Query de Migración:
-- INSERT INTO usuario_roles (usuario_id, rol_id)
-- SELECT u.id, r.id 
-- FROM usuarios u 
-- JOIN roles r ON r.nombre = u.rol_sistema;
